### ISSUE TITLE
Error Configuration JSON cannot be located : .\MandiantAzureADInvestigator.json

### ISSUE THREAD

**Issue by Mohammedali1010** [mandiant/Mandiant-Azure-AD-Investigator#15]
![image](https://user-images.githubusercontent.com/105363338/167848464-84c6c041-8597-4be7-a79f-ec952a613c09.png)
PS C:\Windows\system32> Invoke-MandiantAllChecks c:\temp
Running all checks...
WARNING: Configuration JSON cannot be located : .\MandiantAzureADInvestigator.json
Write-Warning : Cannot bind argument to parameter 'Message' because it is null.
At C:\Mandiant-Azure-AD-Investigator-master\MandiantAzureADInvestigator.psm1:643 char:36
+             Write-Warning -Message $_
+                                    ~~
    + CategoryInfo          : InvalidData: (:) [Write-Warning], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteWarningCommand

Attached Screenshot for reference. Please advise.

Thanks,
Ali.

**Comment by grayfold3d** [comment]
Try changing to the directory you have the module saved to and executing from there

**Comment by Mohammedali1010** [comment]
> Try changing to the directory you have the module saved to and executing from there
> 

Thank you so much! It works as expected !!
