### ISSUE TITLE
Feature Request: Consider Reporting on Get-ApplicationAccessPolicy

### ISSUE THREAD

**Issue by dotnvo** [mandiant/Mandiant-Azure-AD-Investigator#18]
Sometimes, things have pretty scary permissions, but they are scoped down using [Application Access policies](https://docs.microsoft.com/en-us/powershell/module/exchange/get-applicationaccesspolicy?view=exchange-ps). This is often used for applications that utilize APIs/Perms in Exchange.

It might a nice feature to add this on to the report for Apps. I still think that should warn users, but if they see it's been further secured with an application policy that's a good thing to know about. Looking at it, you may have to cache all of the application policies in a variable and potentially do a `Compare-Object` on like AppID or something in order to tie them to the outputted  object.

**Comment by dotnvo** [comment]
Doesn't look like issues is monitored for this repo so going to close.

**Comment by dmb2168** [comment]
@dotnvo  this has come up on a number of instances using this module in customer environments. I would agree it is useful.
If you want to submit a PR we are happy to review and merge!
